feat: restart song with 'Previous' action
vixalien/muzika pull request #196
Opened 2024-08-02 11:21 UTC by DaPigGuy

Match the common behavior of the 'Previous' action across many music apps such as Spotify/YT Music, where the song is restarted if the 'Previous' is activated on the first song of the queue, or after a 5 second "grace period"

I'm not sure I like accessing the Player within the Queue, but this is the easiest way to implement this. We can reiterate if needed.

Closes #193

2024-08-02 12:13 UTC, vixalien requested changes

2024-08-02 12:13 UTC, vixalien commented on src/player/queue.ts
> +import { Application, get_player } from "src/application.js";
I would like `queue` to not depend on `player` but I guess there is no other way

2024-08-02 12:13 UTC, vixalien commented on src/player/queue.ts
You also need to modify the code for `can-play-next`

2024-08-02 12:15 UTC, DaPigGuy commented on src/player/queue.ts
> +import { Application, get_player } from "src/application.js";
That was my thought too but other ideas would be convoluted

2024-08-02 12:17 UTC, DaPigGuy commented on src/player/queue.ts
I think we can just entirely drop `can-play-previous`

2024-08-02 12:47 UTC, vixalien commented on src/player/queue.ts
> +import { Application, get_player } from "src/application.js";
Alright.

2024-08-02 12:47 UTC, vixalien commented on src/player/queue.ts
Cool. I'll test this in a short while

2024-08-02 12:55 UTC, DaPigGuy commented on src/mpris.ts
> +      if (this.player.queue.position > 0) {
I'm not entirely sure that this is needed

2024-08-02 12:59 UTC, DaPigGuy commented on src/mpris.ts
> +      if (this.player.queue.position > 0) {
In fact, the early return causes mpris to desync if switching songs while 'Repeat Current Song' is enabled

2024-08-03 13:12 UTC, DaPigGuy commented on src/mpris.ts
>      this._on_player_model_changed(this.player.queue.list, 0, 0, 0);
We should probably remove those last 3 args? Seems to have been copied over from gnome-music and then unused.

2024-08-04 16:07 UTC, vixalien commented on src/mpris.ts
>      this._on_player_model_changed(this.player.queue.list, 0, 0, 0);
You can remove it if you think that's a bug. I will test it when I review the app.

2024-08-12 17:17 UTC, vixalien commented on src/player/queue.ts
> +      return null;
shouldn't this return `this.current`?

2024-08-13 11:51 UTC, DaPigGuy commented on src/player/queue.ts
> +      return null;
Yes

2024-08-22 22:03 UTC, vixalien commented
Is this ready for review?

2024-08-22 23:01 UTC, DaPigGuy commented
Yes

2024-08-23 17:11 UTC, vixalien approved these changes

2024-08-23 17:11 UTC, merged