chore: fix end margin for album/artist list
vixalien/muzika pull request #206
Opened 2024-09-22 14:14 UTC by diegopvlk

fix #205

2024-09-22 17:57 UTC, vixalien requested changes

2024-09-22 17:57 UTC, vixalien commented on src/components/playlist/columnview/columns/menu.ts
>      const box = Gtk.Box.new(Gtk.Orientation.HORIZONTAL, 3);
You can use easier syntax 

```js
const box = new Gtk.Box({
  orientation: ...,
  spacing: ...,
  margin_end: ...
});
```

2024-09-22 23:29 UTC, vixalien requested changes

2024-09-22 23:29 UTC, vixalien commented on src/components/playlist/columnview/columns/menu.ts
> +      margin_end: 14
Please fix the lint error, by adding a trailing semicolon here

2024-09-22 23:41 UTC, DaPigGuy commented on src/components/playlist/columnview/columns/menu.ts
> +      margin_end: 14
Yes

2024-09-22 23:42 UTC, DaPigGuy approved these changes

2024-09-23 00:10 UTC, vixalien approved these changes

2024-09-23 00:10 UTC, vixalien commented
Thank you!

2024-09-23 00:12 UTC, merged