Add Japanese translation
vixalien/muzika pull request #39
Opened 2023-07-23 18:33 UTC by maboroshin

2023-07-23 21:20 UTC, vixalien requested changes

2023-07-23 21:20 UTC, vixalien commented on po/ja.po
> +msgstr "検索..."
use ellipsis "…" instead of 3 dots "..."

2023-07-23 21:20 UTC, vixalien commented on po/ja.po
> +msgstr "Muzika について(_A)"
seems like you forgot to add an underline. I'm not sure how it works in Japanese, but the letter just after the underline is highlighted when you tap and hold the "Alt" key for easy access

2023-07-23 21:20 UTC, vixalien commented on po/ja.po
> +msgstr "次の語句の検索結果: %s"
I think there is some inconsistency. the "Did you mean: %s" got translated as "もしかして？: %s":

1. I'm not sure where the question mark came from "?") but note that I'm not a Japanese speaker
2. why is there a space between the colon in the "Did you mean" case but not on this line?

2023-07-23 21:20 UTC, vixalien commented on po/ja.po
> +msgstr "続行しますか？"
is the space at the end of this sentence necessary?

2023-07-23 21:42 UTC, maboroshin commented on po/ja.po
> +msgstr "Muzika について(_A)"
No problem. Putting it in parentheses at the end is the Japanese method. Microsoft's Notepad for Japanese:
![image](https://github.com/vixalien/muzika/assets/41102508/373088b9-9ce8-4eaa-8b03-9a21ea492a0f)

2023-07-23 21:52 UTC, maboroshin commented on po/ja.po
> +msgstr "次の語句の検索結果: %s"
Both are Google's fixed translations of Japanese. However, "?" was my misunderstanding. It was a memory of Piped's translation: https://hosted.weblate.org/translate/piped/frontend/ja/?checksum=48c1aae424893cce

![image](https://github.com/vixalien/muzika/assets/41102508/7fcbfdd9-1b47-4dd5-b24c-3561e8c4c356)
https://markezine.jp/article/detail/6447

1. So  I would remove the "?" but it is not strange if it remains.
2. There is no space in front of the colon. There is space after. There is no difference here.

2023-07-23 21:57 UTC, vixalien commented on po/ja.po
> +msgstr "次の語句の検索結果: %s"
okay

2023-07-23 21:57 UTC, maboroshin commented on po/ja.po
> +msgstr "続行しますか？"
It would be the same as the "Did you mean" space above.

There is no colon. it must appear that way because of the 2-byte character rendering.

2023-07-23 21:57 UTC, maboroshin commented on po/ja.po
> +msgstr "検索..."
It's fixed.

2023-07-24 08:35 UTC, vixalien commented on po/ja.po
> +msgstr "Muzika について(_A)"
oh alright. gotcha! I didn't see the shortcut in the parens

2023-07-24 08:36 UTC, vixalien requested changes

2023-07-24 08:36 UTC, vixalien commented on po/ja.po
> +msgstr "キーボードショートカット(K)"
there should be an underline before the "K" in `(K)`
```suggestion
msgstr "キーボードショートカット(_K)"
```

2023-07-24 08:36 UTC, vixalien commented on po/ja.po
> +msgstr "続行しますか？"
oh. I see. I didn't see this sorry

2023-07-24 08:55 UTC, maboroshin commented on po/ja.po
> +msgstr "キーボードショートカット(K)"
Yes this is my typo. Thank you.

2023-07-26 11:09 UTC, vixalien approved these changes

2023-07-26 11:09 UTC, merged