Draft: Video Player
vixalien/muzika pull request #47
Opened 2023-08-01 08:19 UTC by vixalien

![image](https://github.com/vixalien/muzika/assets/37999241/36e138e4-832d-4665-ae3f-51862ad25e3b)

need to iron out a few thing:

- [ ] smaller bar for videos on larger screens (see [GNOME Videos potential mockups](https://gitlab.gnome.org/Teams/Design/app-mockups/-/blob/master/videos/videos.png)
- [ ] thumbnail in player view should show cover art or video preview if possible
- [ ] UI to switch between video and song versions of a track

2023-08-03 13:17 UTC, vixalien commented
also note that this pull request effectively stops arm builds as they would take [upwards of 2 hours](https://github.com/vixalien/muzika/actions/runs/5725652328/job/15514554879) because of compiling for `gtk4paintablesink`.

Not only is the time long for "continuous integration" but also Github CI has limits, and it would not be long until we hit them.

the ARM builds can be reintroduced if/when either of these happen (outside of my control):

- Github Actions, and by extension `flatpak-github-builder` [provides an ARM container](https://github.com/actions/runner-images/issues/5631). this would [stop us relying on emulating ARM inside QEMU](https://github.com/flatpak/flatpak-github-actions/issues/124)) and improve build times significantly. [See PR](https://github.com/flatpak/flatpak-github-actions/pull/85)
- `gtk-plugins-rs` begins to get shipped in with the other Gstreamer stuff in the GNOME Flatpak Runtime [See PR](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1502)

2023-08-03 15:40 UTC, vixalien commented
more/better/updated screenshots

![Screenshot from 2023-08-03 17-29-55](https://github.com/vixalien/muzika/assets/37999241/8223a7cc-a494-49fd-af7a-cf3379ae30af)

Normal View

![image](https://github.com/vixalien/muzika/assets/37999241/dde4f761-f7eb-4e05-a360-7fe334230515)

Mobile View

![Screenshot from 2023-08-03 17-30-31](https://github.com/vixalien/muzika/assets/37999241/8af5f992-262f-4288-bac8-8d6eb229b065)

Normal Browsing

![image](https://github.com/vixalien/muzika/assets/37999241/4edd2fc9-b321-4b52-a5f0-6208f112a2f2)

Full screen

2023-08-04 10:23 UTC, DaPigGuy reviewed
Just a few comments, great work with the app as always!

2023-08-04 10:23 UTC, DaPigGuy commented on src/player/queue.ts
> +    const track = this.current?.object;
Completely style choice, feel free to ignore, but this could be write as

```js
return this.current?.object?.videoType !== "MUSIC_VIDEO_TYPE_ATV";
```

2023-08-04 10:23 UTC, DaPigGuy commented on src/player/queue.ts
> +    let final_track: ObjectContainer<QueueMeta>;
Consider initializing as `track` so you can get rid of the `else` statements

2023-08-04 10:23 UTC, DaPigGuy commented on src/player/queue.ts
> +    return track;
Shouldn't this return `final_track`?

2023-08-04 10:23 UTC, DaPigGuy commented on src/player/index.ts
> +          AudioQuality[audio_quality];
Again, style choice, feel free to ignore

```js
return audio_quality === AudioQuality.auto || e.audio_quality == AudioQuality[audio_quality];
```

2023-08-04 10:23 UTC, DaPigGuy commented on data/com.vixalien.muzika.gschema.xml
Indentation issues throughout the diff

2023-08-04 10:23 UTC, DaPigGuy commented on data/ui/window.blp
>    Adw.ToolbarView toolbar_view {
Missing indentation

2023-08-04 10:24 UTC, DaPigGuy commented on src/player/index.ts
> +          AudioQuality[audio_quality];
Same for `video_quality`

2023-08-06 18:55 UTC, vixalien commented on data/com.vixalien.muzika.gschema.xml
what indentation issues are you talking about?

2023-08-06 18:56 UTC, vixalien commented on src/components/player/video/full.ts
> +  private setup_player() {
I've tried that in the past and GJS throwed errors at me. will try again to see.

2023-08-06 19:03 UTC, vixalien commented on src/components/player/video/full.ts
> +  private setup_player() {
yep it won't work. says:

```
(com.vixalien.muzika:2): Gtk-CRITICAL **: 21:02:10.219: Error building template class 'FullVideoControls' for an instance of type 'FullVideoControls': .:0:0 Template parent type 'AdwBin' does not match instance parent type 'BaseVideoControls'.
```

2023-08-06 21:54 UTC, DaPigGuy commented on data/com.vixalien.muzika.gschema.xml
LInes 5-9, 12-21, 41-44, 46-49

2023-08-06 22:26 UTC, vixalien commented on data/com.vixalien.muzika.gschema.xml
ah lol. its because of tabs vs spaces

2023-08-15 19:59 UTC, vixalien commented
while this PR is generally complete, there are a few things missing:

- one is that streams are a bit wonky (see above GJS issues) and hence videos may end sooner (looking for a fix)
- the player controls for phone doesn't really work. this is because hovering to reveal the player controls won't work if there is no mouse pointer. I can fix this, only if there was a way to know that the current device has no mouses/pointers.

I'm however marking this as ready for review, so as to advance things and work on other important things.

2023-08-18 08:06 UTC, DaPigGuy requested changes

2023-08-18 08:34 UTC, vixalien commented on src/components/player/video/util.ts
> +  return code;
I think the current code looks cleaner and is more obvious.

2023-08-18 08:34 UTC, vixalien commented on src/player/index.ts
> +    if (streams.filter(format_has_audio).length === 0) {
thanks!

2023-08-18 08:49 UTC, vixalien commented on src/player/queue.ts
> +      position = this.position - 1;
nice catch!

2023-08-18 08:50 UTC, vixalien commented on src/player/index.ts
> +        counterpart_videoId && now_playing_videoId &&
the thing is if I check equality and they are both undefined, the equality check will succeed.

2023-08-18 08:52 UTC, vixalien commented on src/player/index.ts
> +        this.timestamp != 0
what do you mean?

2023-08-18 08:55 UTC, DaPigGuy commented on src/player/index.ts
> +        counterpart_videoId && now_playing_videoId &&
You can simply check one, e.g `counterpart_videoId && counterpart_videoId === now_playing_videoId`

2023-08-18 08:56 UTC, DaPigGuy commented on src/player/index.ts
> +        this.timestamp != 0
`!==` vs `!=`

2023-08-18 08:56 UTC, vixalien commented on src/player/index.ts
> +        counterpart_videoId && now_playing_videoId &&
true.

2023-08-18 18:02 UTC, merged

2023-08-20 10:39 UTC, vixalien commented
im fucking happy to report that the issue where the audio/video would clip randomly and songs would not end correctly is now fixed by d906308137a2b38abcaeb9851dfb92f11e251226 in main!!!!

the issue was very maddening.

as a bonus, now we only play webm (v8) files (instead of mp4) which:

- has a lower file size
- has better quality for videos (due to the way YTM compresses stuff) 
- fix the above issue

webm should be less compatible, but as this is gstreamer in a flatpak, I doubt it will make a difference

2023-08-20 10:59 UTC, vixalien commented
welp seems like i spoke too soon. dashdemux doesn't seem to be switching video tracks when quality is set to 'auto'